name = "f2fpos-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./build/client"

[env.production]
account_id = "your-account-id"

[[routes]]
pattern = "your-domain.com/*"
zone_id = "your-zone-id"